services:
  db:
    image: postgres:16 
    container_name: maxim-portfolio-db
    restart: unless-stopped  # Автоматически перезапускать, если контейнер упал (кроме случая, когда остановили вручную)
    environment:
      POSTGRES_USER: maxim 
      POSTGRES_PASSWORD: maxim
      POSTGRES_DB: maxim_portfolio
    ports:
      - '5432:5432'  # Проброс порта: слева порт на сервере, справа порт внутри контейнера
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U maxim -d maxim_portfolio']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    pull_policy: build  # Каждый docker compose up пересобирает образ бэкенда
    container_name: maxim-portfolio-backend
    restart: unless-stopped
    ports:
      - '3001:3001'  # Порт бэкенда на сервере: порт внутри контейнера
    environment:
      PORT: 3001
      DATABASE_URL: postgres://maxim:maxim@db:5432/maxim_portfolio
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy

  microservice:
    build: ./backend-microservice
    container_name: maxim-portfolio-microservice
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: maxim-portfolio-frontend
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: http://backend:3001
      VITE_MICROSERVICE_URL: http://microservice:3002
    ports:
      - '5173:5173'
    depends_on:
      - backend
      - microservice

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - grafana_data:/var/lib/grafana
    mem_limit: 256m
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: